version: '3'
services:
    api2:
        build: .
        image: api2
        command: api2
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - api2
